var Data = {  
   "cells":[  
      {  
         "type":"basic.Circle",
         "size":{  
            "width":80,
            "height":80
         },
         "position":{  
            "x":480,
            "y":10
         },
         "angle":0,
         "id":"d2758428-c41b-469a-9f9c-8eed6bbb8014",
         "z":1,
         "attrs":{  
            "circle":{  
               "fill":"transparent",
               "stroke":"#b75d32",
               "width":50,
               "height":30,
               "stroke-width":8,
               "stroke-dasharray":"10,5"
            },
            "text":{  
               "font-size":15,
               "text":"Learn Rappid",
               "fill":"#b75d32",
               "font-family":"Roboto Condensed",
               "font-weight":"Bold",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"erd.Relationship",
         "size":{  
            "width":170,
            "height":120
         },
         "position":{  
            "x":435,
            "y":154
         },
         "angle":0,
         "id":"8eea851d-f939-4b70-bd5c-dc8c6a7037cd",
         "z":2,
         "attrs":{  
            ".outer":{  
               "fill":"#4b4a67",
               "stroke":"transparent",
               "stroke-dasharray":"0"
            },
            "text":{  
               "text":"Have experience?",
               "font-family":"Roboto Condensed",
               "font-size":13,
               "font-weight":"Normal",
               "fill":"#f6f6f6",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"basic.Rect",
         "position":{  
            "x":190,
            "y":220
         },
         "size":{  
            "width":110,
            "height":50
         },
         "angle":0,
         "id":"c89958a4-a6b6-41b0-88d2-a2ab3b5ce4ca",
         "z":4,
         "attrs":{  
            "rect":{  
               "fill":"#feb663",
               "stroke":"#3c4260",
               "width":50,
               "height":30,
               "rx":2,
               "ry":2,
               "stroke-width":3,
               "stroke-dasharray":"0"
            },
            "text":{  
               "fill":"#3c4260",
               "text":"No",
               "font-size":13,
               "font-family":"Roboto Condensed",
               "font-weight":"Bold",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"basic.Rect",
         "position":{  
            "x":690,
            "y":220
         },
         "size":{  
            "width":110,
            "height":50
         },
         "angle":0,
         "id":"c89958a4-a6b6-41b0-88d2-a2ab3b5ce4cx",
         "z":4,
         "attrs":{  
            "rect":{  
               "fill":"#feb663",
               "stroke":"#3c4260",
               "width":50,
               "height":30,
               "rx":2,
               "ry":2,
               "stroke-width":3,
               "stroke-dasharray":"0"
            },
            "text":{  
               "fill":"#3c4260",
               "text":"Yes",
               "font-size":13,
               "font-family":"Roboto Condensed",
               "font-weight":"Bold",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"app.Link",
         "router":{  
            "name":"normal"
         },
         "connector":{  
            "name":"normal"
         },
         "source":{  
            "id": "d2758428-c41b-469a-9f9c-8eed6bbb8014"
         },
         "target":{  
            "id":"8eea851d-f939-4b70-bd5c-dc8c6a7037cd"
         },
         "id":"c408eb1b-1f51-4e41-9158-c21f2b5d59bd",
         "z":60,
         "attrs":{  

         }
      },
      {  
         "type":"app.Link",
         "router":{  
            "name":"normal"
         },
         "connector":{  
            "name":"normal"
         },
         "source":{  
            "id":"8eea851d-f939-4b70-bd5c-dc8c6a7037cd"
         },
         "target":{  
            "id":"c89958a4-a6b6-41b0-88d2-a2ab3b5ce4cx"
         },
         "id":"59b5221e-f031-40c1-9b9a-70359c6e6808",
         "z":60,
         "attrs":{  

         }
      },
      {  
         "type":"app.Link",
         "router":{  
            "name":"normal"
         },
         "connector":{  
            "name":"normal"
         },
         "source":{  
            "id":"8eea851d-f939-4b70-bd5c-dc8c6a7037cd"
         },
         "target":{  
            "id": "c89958a4-a6b6-41b0-88d2-a2ab3b5ce4ca"
         },
         "id":"59b5221e-f031-40c1-9b9a-70359c6e6810",
         "z":60,
         "attrs":{  

         }
      }
   ]
}


module.exports = Data;