var data = {  
   "cells":[  
      {  
         "type":"basic.Circle",
         "size":{  
            "width":80,
            "height":80
         },
         "position":{  
            "x":480,
            "y":10
         },
         "angle":0,
         "id":"d2758428-c41b-469a-9f9c-8eed6bbb8014",
         "z":1,
         "attrs":{  
            "circle":{  
               "fill":"transparent",
               "stroke":"#b75d32",
               "width":50,
               "height":30,
               "stroke-width":8,
               "stroke-dasharray":"10,5"
            },
            "text":{  
               "font-size":15,
               "text":"Fire\\nIncident",
               "fill":"#b75d32",
               "font-family":"Roboto Condensed",
               "font-weight":"Bold",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"erd.Relationship",
         "size":{  
            "width":170,
            "height":120
         },
         "position":{  
            "x":435,
            "y":154
         },
         "angle":0,
         "id":"8eea851d-f939-4b70-bd5c-dc8c6a7037cd",
         "z":2,
         "attrs":{  
            ".outer":{  
               "fill":"#4b4a67",
               "stroke":"transparent",
               "stroke-dasharray":"0"
            },
            "text":{  
               "text":"Auto Alarm\\nactivated?",
               "font-family":"Roboto Condensed",
               "font-size":13,
               "font-weight":"Normal",
               "fill":"#f6f6f6",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"basic.Rect",
         "position":{  
            "x":690,
            "y":189
         },
         "size":{  
            "width":110,
            "height":50
         },
         "angle":0,
         "id":"c89958a4-a6b6-41b0-88d2-a2ab3b5ce4ca",
         "z":4,
         "attrs":{  
            "rect":{  
               "fill":"#feb663",
               "stroke":"#3c4260",
               "width":50,
               "height":30,
               "rx":2,
               "ry":2,
               "stroke-width":3,
               "stroke-dasharray":"0"
            },
            "text":{  
               "fill":"#3c4260",
               "text":"Activate\\nevacuation",
               "font-size":13,
               "font-family":"Roboto Condensed",
               "font-weight":"Bold",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"basic.Rect",
         "position":{  
            "x":860,
            "y":595
         },
         "size":{  
            "width":110,
            "height":70
         },
         "angle":0,
         "id":"c7459d76-693a-4db3-a82c-2c45d9822c17",
         "z":6,
         "attrs":{  
            "rect":{  
               "fill":"#dcd7d7",
               "stroke":"#3c4260",
               "width":50,
               "height":30,
               "rx":2,
               "ry":2,
               "stroke-width":3,
               "stroke-dasharray":"0"
            },
            "text":{  
               "fill":"#3c4260",
               "text":"Evacuees report\\nto Gathering\\nPoint / Safe Area",
               "font-size":13,
               "font-family":"Roboto Condensed",
               "font-weight":"Normal",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      },
      {  
         "type":"basic.Rect",
         "position":{  
            "x":860,
            "y":965
         },
         "size":{  
            "width":110,
            "height":70
         },
         "angle":0,
         "id":"89c096ef-433e-4708-a0d9-302ca9807dc4",
         "z":9,
         "attrs":{  
            "rect":{  
               "fill":"#dcd7d7",
               "stroke":"#3c4260",
               "width":50,
               "height":30,
               "rx":2,
               "ry":2,
               "stroke-width":3,
               "stroke-dasharray":"0"
            },
            "text":{  
               "fill":"#3c4260",
               "text":"Floor Marshals\\nbrief Crisis\\nManagement\\nTeam using floor\\nplans",
               "font-size":13,
               "font-family":"Roboto Condensed",
               "font-weight":"Normal",
               "stroke-width":0
            },
            ".":{  
               "data-tooltip-position":"left",
               "data-tooltip-position-selector":".joint-stencil"
            }
         }
      }
   ]
}

module.exports = data;